# Generated by Django 2.0.4 on 2018-04-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_surveyanswer_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyanswer',
            name='title',
        ),
    ]
