# Generated by Django 2.0.4 on 2018-04-23 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180423_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswer',
            name='title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Surveytitle'),
        ),
    ]
