# Generated by Django 2.0.4 on 2018-04-23 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_surveyanswer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='surveytitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Surveytitle'),
        ),
    ]
