# Generated by Django 2.0.4 on 2018-04-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20180423_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyquestion',
            old_name='title',
            new_name='surveytitle',
        ),
    ]
