# Generated by Django 2.0.4 on 2018-04-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180423_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyanswer',
            old_name='surveytitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='surveyquestion',
            old_name='surveytitle',
            new_name='title',
        ),
    ]
